name: permissions_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  permission_handler: ^11.4.0
  sensors_plus: ^6.1.1
  share_plus: ^10.1.4

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
